core:
  build: ./core
  ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
  volumes:
    - /opt/dockermail/settings:/mail_settings
    - /opt/dockermail/vmail:/vmail
  volumes_from:
    - mailman
  links:
   - opendkim
   - amavis
   - mailman
opendkim:
  build: ./opendkim
  volumes:
    - /opt/dockermail/settings:/mail_settings
amavis:
  build: ./amavis
  volumes:
    - /opt/dockermail/settings:/mail_settings
mailman:
  build: ./mailman
  volumes:
    - /opt/dockermail/mailman:/mailman/var
  environment:
    - VIRTUAL_HOST=mailman.sesc.eu
    - LETSENCRYPT_EMAIL=mail@sesc.eu
